import { useEffect, useState } from "react";
import DashboardLayout from "../../layouts/DashboardLayout";
import {
  Brain,
  Trash2,
  CheckCircle,
  XCircle,
  RotateCcw,
} from "lucide-react";

import {
  getQuizzes,
  deleteQuiz,
} from "../../services/quizService";

export default function Quiz() {
  const [quizzes, setQuizzes] = useState([]);
  const [loading, setLoading] = useState(true);

  const [currentQuestion, setCurrentQuestion] =
    useState(0);

  const [selectedOption, setSelectedOption] =
    useState("");

  const [submitted, setSubmitted] =
    useState(false);

  const [score, setScore] =
    useState(0);

  const [finished, setFinished] =
    useState(false);

  async function loadQuizzes() {
    try {
      const data = await getQuizzes();
      setQuizzes(data);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    loadQuizzes();
  }, []);

  async function handleDelete(id) {
    await deleteQuiz(id);
    loadQuizzes();
  }

  function handleSubmit() {
    if (!selectedOption) return;

    const correctAnswer =
      quizzes[currentQuestion].answer
        ?.trim()
        .toLowerCase();

    const chosenAnswer =
      selectedOption
        ?.trim()
        .toLowerCase();

    if (chosenAnswer === correctAnswer) {
      setScore((prev) => prev + 1);
    }

    setSubmitted(true);
  }

  function nextQuestion() {
    if (
      currentQuestion + 1 <
      quizzes.length
    ) {
      setCurrentQuestion((prev) => prev + 1);
      setSelectedOption("");
      setSubmitted(false);
    } else {
      setFinished(true);
    }
  }

  function restartQuiz() {
    setCurrentQuestion(0);
    setSelectedOption("");
    setSubmitted(false);
    setScore(0);
    setFinished(false);
  }

  return (
    <DashboardLayout>

      <div className="mb-10">

        <h1 className="text-4xl font-bold">
          Quiz
        </h1>

        <p className="text-gray-500 mt-2">
          Practice quizzes generated by AI.
        </p>

      </div>
            {loading ? (

        <div className="text-center py-10">
          Loading...
        </div>

      ) : quizzes.length === 0 ? (

        <div className="bg-white rounded-3xl border border-violet-100 p-16 text-center">

          <Brain
            size={60}
            className="mx-auto text-violet-500"
          />

          <h2 className="text-2xl font-semibold mt-5">
            No Quiz Available
          </h2>

          <p className="text-gray-500 mt-3">
            Generate a quiz from the AI Workspace.
          </p>

        </div>

      ) : finished ? (

        <div className="bg-white rounded-3xl border border-violet-100 p-12 text-center shadow-sm">

          <Brain
            size={70}
            className="mx-auto text-violet-600"
          />

          <h2 className="text-4xl font-bold mt-6">
            Quiz Completed 🎉
          </h2>

          <p className="text-2xl mt-8">
            Your Score
          </p>

          <h1 className="text-6xl font-bold text-violet-600 mt-3">
            {score} / {quizzes.length}
          </h1>

          <button
            onClick={restartQuiz}
            className="mt-10 bg-violet-600 hover:bg-violet-700 text-white px-8 py-4 rounded-xl flex items-center gap-2 mx-auto"
          >
            <RotateCcw size={20} />
            Restart Quiz
          </button>

        </div>

      ) : (

        <div className="bg-white rounded-3xl border border-violet-100 shadow-sm p-8">

          <div className="flex justify-between items-center mb-6">

            <div>

              <h2 className="text-2xl font-bold">
                Question {currentQuestion + 1} of {quizzes.length}
              </h2>

              <p className="text-gray-500 mt-1">
                Choose the correct answer.
              </p>

            </div>

            <button
              onClick={() =>
                handleDelete(quizzes[currentQuestion].id)
              }
              className="text-red-500 hover:text-red-700"
            >
              <Trash2 size={22} />
            </button>

          </div>

          <div className="w-full bg-gray-200 rounded-full h-3 mb-8">

            <div
              className="bg-violet-600 h-3 rounded-full transition-all duration-500"
              style={{
                width: `${((currentQuestion + 1) / quizzes.length) * 100}%`,
              }}
            />

          </div>

          <h2 className="text-2xl font-semibold mb-8 leading-9">

            {quizzes[currentQuestion].question}

          </h2>

          <div className="space-y-4">{quizzes[currentQuestion].options.map((option, index) => {

  const correctAnswer =
    quizzes[currentQuestion].answer
      ?.trim()
      .toLowerCase();

  const optionValue =
    option?.trim().toLowerCase();

  const isCorrect =
    optionValue === correctAnswer;

  const isSelected =
    selectedOption === option;

  return (

    <label
      key={index}
      className={`flex items-center gap-4 border rounded-2xl p-4 cursor-pointer transition

      ${
        submitted
          ? isCorrect
            ? "border-green-500 bg-green-50"
            : isSelected
            ? "border-red-500 bg-red-50"
            : "border-gray-200"
          : isSelected
          ? "border-violet-500 bg-violet-50"
          : "border-gray-200 hover:border-violet-300"
      }`}
    >

      <input
        type="radio"
        name="quizOption"
        disabled={submitted}
        checked={selectedOption === option}
        onChange={() =>
          setSelectedOption(option)
        }
      />

      <span className="flex-1">
        {option}
      </span>

      {submitted && isCorrect && (
        <CheckCircle
          size={20}
          className="text-green-600"
        />
      )}

    </label>

  );

})}

</div>

{!submitted ? (

  <button
    disabled={!selectedOption}
    onClick={handleSubmit}
    className="mt-8 bg-violet-600 hover:bg-violet-700 disabled:bg-gray-300 text-white px-8 py-3 rounded-xl"
  >
    Submit Answer
  </button>

) : (<div className="mt-8">

  {selectedOption.trim().toLowerCase() ===
  quizzes[currentQuestion].answer
    .trim()
    .toLowerCase() ? (

    <div className="flex items-center gap-3 text-green-600 font-semibold text-lg">

      <CheckCircle size={24} />

      Correct Answer! 🎉

    </div>

  ) : (

    <div>

      <div className="flex items-center gap-3 text-red-600 font-semibold text-lg">

        <XCircle size={24} />

        Wrong Answer

      </div>

      <p className="mt-4 text-lg">

        <span className="font-semibold">
          Your Answer:
        </span>{" "}

        {selectedOption}

      </p>

      <p className="mt-2 text-lg">

        <span className="font-semibold">
          Correct Answer:
        </span>{" "}

        {quizzes[currentQuestion].answer}

      </p>

    </div>

  )}

  <button
    onClick={nextQuestion}
    className="mt-8 bg-violet-600 hover:bg-violet-700 text-white px-8 py-3 rounded-xl"
  >
    {currentQuestion === quizzes.length - 1
      ? "Finish Quiz"
      : "Next Question"}
  </button>

</div>          )}

        </div>

      )}

    </DashboardLayout>
  );
}